<a href="https://colab.research.google.com/github/Aman2269/OCR/blob/main/kerasss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install keras-ocr

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 46.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 908.3/908.3 kB 58.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.7/50.7 kB 6.1 MB/s eta 0:00:00


In [ ]:
import keras_ocr
pipeline=keras_ocr.pipeline.Pipeline()

Looking for /root/.keras-ocr/craft_mlt_25k.h5


Instructions for updating:
Use `tf.image.resize(...method=ResizeMethod.BILINEAR...)` instead.


Looking for /root/.keras-ocr/crnn_kurapan.h5


In [ ]:
text=pipeline.recognize(["lic1.jpg"])

2/2 [==============================] - 18s 9s/step


In [ ]:
text

[[('florida',
   array([[ 34.,  25.],
          [253.,  25.],
          [253.,  89.],
          [ 34.,  89.]], dtype=float32)),
  ('usa',
   array([[712.,  32.],
          [753.,  32.],
          [753.,  50.],
          [712.,  50.]], dtype=float32)),
  ('a',
   array([[671.,  40.],
          [712.,  40.],
          [712.,  85.],
          [671.,  85.]], dtype=float32)),
  ('driver',
   array([[319.,  63.],
          [432.,  63.],
          [432.,  90.],
          [319.,  90.]], dtype=float32)),
  ('license',
   array([[436.0596  ,  62.854942],
          [558.18396 ,  64.04062 ],
          [557.9258  ,  90.64005 ],
          [435.80136 ,  89.45438 ]], dtype=float32)),
  ('ans',
   array([[  2.3803463, 116.151505 ],
          [ 66.61967  ,  71.84852  ],
          [ 91.82514  , 108.396454 ],
          [ 27.585823 , 152.69943  ]], dtype=float32)),
  ('e',
   array([[740.,  96.],
          [760.,  96.],
          [760., 124.],
          [740., 124.]], dtype=float32)),
  ('7624a3',
   array

In [ ]:
for i in range(len(text[0])):
  print(text[0][i][0])



florida
usa
a
driver
license
ans
e
7624a3
giow75
class
dln
ad
co
cedar
jeremiah
3351
bagwell
avenue

boggsville
fl
34448
0310311989
m
dob
sex
15
0310312024
571
lahgt
exp
none
none
rest
end
12
3a
safe
driver
s
donor
031031201
6
ss
aa
gunagon
aa123456789
dd
operation
ofa
vehicle
motor
constitutes
consentto
sobriety
required
test
by
lawa
any
